import type { Inventory, Scenario, Zone } from './types'

export const DEFAULT_SCENARIO: Scenario = {
  hazard: 'flood',
  intensity: 72,
  horizonHours: 18,
  commsOutage: 28,
  roadDamage: 34,
  hospitalLoad: 61,
  resourceBudget: 76,
  equityWeight: 68,
  privacyMode: true,
  fieldNote:
    'River gauges rising near Dock Ward. Two bridges limited to one lane. Clinic backup power is unstable.',
}

export const BASE_INVENTORY: Inventory = {
  rescueTeams: 28,
  medicalTeams: 18,
  buses: 42,
  drones: 16,
  pumps: 20,
  generators: 14,
  shelterKits: 54,
}

export const CITY_ZONES: Zone[] = [
  {
    id: 'dock-ward',
    name: 'Dock Ward',
    district: 'Harbor',
    x: 13,
    y: 67,
    population: 46300,
    vulnerability: 83,
    elevation: 18,
    vegetation: 18,
    concrete: 72,
    riverExposure: 94,
    roadAccess: 46,
    shelterCapacity: 5200,
    hospitalBeds: 38,
    assets: ['clinic', 'warehouse', 'waterPlant'],
    neighbors: ['old-market', 'riverbend', 'south-bank'],
  },
  {
    id: 'old-market',
    name: 'Old Market',
    district: 'Central',
    x: 29,
    y: 48,
    population: 58200,
    vulnerability: 64,
    elevation: 36,
    vegetation: 14,
    concrete: 88,
    riverExposure: 72,
    roadAccess: 62,
    shelterCapacity: 8300,
    hospitalBeds: 124,
    assets: ['clinic', 'school', 'warehouse'],
    neighbors: ['dock-ward', 'university-hill', 'midtown'],
  },
  {
    id: 'university-hill',
    name: 'University Hill',
    district: 'North',
    x: 43,
    y: 26,
    population: 39700,
    vulnerability: 34,
    elevation: 82,
    vegetation: 41,
    concrete: 54,
    riverExposure: 20,
    roadAccess: 86,
    shelterCapacity: 9200,
    hospitalBeds: 210,
    assets: ['clinic', 'school', 'substation'],
    neighbors: ['old-market', 'midtown', 'ridge-park'],
  },
  {
    id: 'midtown',
    name: 'Midtown',
    district: 'Central',
    x: 51,
    y: 49,
    population: 77100,
    vulnerability: 48,
    elevation: 44,
    vegetation: 22,
    concrete: 92,
    riverExposure: 45,
    roadAccess: 78,
    shelterCapacity: 11200,
    hospitalBeds: 166,
    assets: ['clinic', 'substation', 'warehouse'],
    neighbors: ['old-market', 'university-hill', 'rail-yard', 'east-gate'],
  },
  {
    id: 'riverbend',
    name: 'Riverbend',
    district: 'West',
    x: 21,
    y: 82,
    population: 35400,
    vulnerability: 78,
    elevation: 12,
    vegetation: 32,
    concrete: 53,
    riverExposure: 98,
    roadAccess: 41,
    shelterCapacity: 3600,
    hospitalBeds: 22,
    assets: ['school', 'waterPlant'],
    neighbors: ['dock-ward', 'south-bank', 'old-market'],
  },
  {
    id: 'south-bank',
    name: 'South Bank',
    district: 'South',
    x: 40,
    y: 82,
    population: 48600,
    vulnerability: 71,
    elevation: 20,
    vegetation: 24,
    concrete: 67,
    riverExposure: 86,
    roadAccess: 52,
    shelterCapacity: 6100,
    hospitalBeds: 54,
    assets: ['school', 'warehouse'],
    neighbors: ['dock-ward', 'riverbend', 'rail-yard'],
  },
  {
    id: 'rail-yard',
    name: 'Rail Yard',
    district: 'Industrial',
    x: 59,
    y: 74,
    population: 29100,
    vulnerability: 69,
    elevation: 29,
    vegetation: 16,
    concrete: 79,
    riverExposure: 69,
    roadAccess: 59,
    shelterCapacity: 2700,
    hospitalBeds: 18,
    assets: ['warehouse', 'substation'],
    neighbors: ['south-bank', 'midtown', 'east-gate'],
  },
  {
    id: 'east-gate',
    name: 'East Gate',
    district: 'East',
    x: 78,
    y: 56,
    population: 52400,
    vulnerability: 55,
    elevation: 39,
    vegetation: 28,
    concrete: 75,
    riverExposure: 40,
    roadAccess: 73,
    shelterCapacity: 7400,
    hospitalBeds: 72,
    assets: ['school', 'substation'],
    neighbors: ['midtown', 'rail-yard', 'solar-heights', 'cedar-grove'],
  },
  {
    id: 'ridge-park',
    name: 'Ridge Park',
    district: 'North',
    x: 67,
    y: 19,
    population: 31800,
    vulnerability: 39,
    elevation: 91,
    vegetation: 88,
    concrete: 24,
    riverExposure: 10,
    roadAccess: 64,
    shelterCapacity: 4500,
    hospitalBeds: 36,
    assets: ['school'],
    neighbors: ['university-hill', 'cedar-grove'],
  },
  {
    id: 'cedar-grove',
    name: 'Cedar Grove',
    district: 'Foothills',
    x: 87,
    y: 30,
    population: 26800,
    vulnerability: 44,
    elevation: 76,
    vegetation: 94,
    concrete: 18,
    riverExposure: 15,
    roadAccess: 48,
    shelterCapacity: 2600,
    hospitalBeds: 14,
    assets: ['waterPlant'],
    neighbors: ['ridge-park', 'east-gate', 'solar-heights'],
  },
  {
    id: 'solar-heights',
    name: 'Solar Heights',
    district: 'East',
    x: 83,
    y: 78,
    population: 40200,
    vulnerability: 52,
    elevation: 53,
    vegetation: 37,
    concrete: 61,
    riverExposure: 32,
    roadAccess: 69,
    shelterCapacity: 5600,
    hospitalBeds: 30,
    assets: ['substation', 'school'],
    neighbors: ['east-gate', 'cedar-grove', 'rail-yard'],
  },
  {
    id: 'airport-loop',
    name: 'Airport Loop',
    district: 'Perimeter',
    x: 66,
    y: 92,
    population: 22400,
    vulnerability: 57,
    elevation: 32,
    vegetation: 29,
    concrete: 81,
    riverExposure: 58,
    roadAccess: 82,
    shelterCapacity: 1800,
    hospitalBeds: 8,
    assets: ['warehouse', 'substation'],
    neighbors: ['rail-yard', 'solar-heights'],
  },
]
